[package]
name = "cas-typescript-sdk-napi"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
napi = "2.16.13"
napi-derive = "2.16.12"
csbindgen = "1.9.1"
cas-lib = "0.2.2"

[build-dependencies]
napi-build = "1"